pool:
  vmImage: vs2017-win2016
trigger:
- buildbranch
pr: none
stages:
- stage: stage_0
  jobs:
  - job: ros_noetic_catkin
    variables:
      CONDA_BLD_PATH: C:\\bld\\
    steps:
    - task: CondaEnvironment@1
      inputs:
        packageSpecs: python=3.6 dataclasses conda-build conda conda-forge::conda-forge-ci-setup=3
          pip boa quetz-client
        installOptions: -c conda-forge/label/boa_dev -c conda-forge
        updateConda: true
      displayName: Install conda-build, boa and activate environment
    - script: '

        set "CI=azure"

        call activate base

        run_conda_forge_build_setup'
      displayName: conda-forge build setup
    - script: '

        set "CI=azure"

        call activate base


        @rem git clone https://github.com/thesnakepit/boa

        @rem cd boa

        @rem pip install -e .

        @rem cd ..


        conda config --append channels defaults

        conda config --add channels conda-forge

        conda config --add channels robostack

        conda config --set channel_priority strict


        @rem conda info

        @rem conda config --show-sources


        conda remove --force m2-git


        @rem conda list --show-channel-urls


        cp recipes/%CURRENT_BUILD_PKG_NAME%.yaml ./recipe.yaml


        boa build .


        @rem conda.exe build "recipe" -m .ci_support/%CONFIG%.yaml

        '
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_BUILD_PKG_NAME: ros-noetic-catkin
        PYTHONUNBUFFERED: 1
      displayName: Build ros-noetic-catkin
- stage: stage_1
  jobs:
  - job: ros_noetic_genmsg
    variables:
      CONDA_BLD_PATH: C:\\bld\\
    steps:
    - task: CondaEnvironment@1
      inputs:
        packageSpecs: python=3.6 dataclasses conda-build conda conda-forge::conda-forge-ci-setup=3
          pip boa quetz-client
        installOptions: -c conda-forge/label/boa_dev -c conda-forge
        updateConda: true
      displayName: Install conda-build, boa and activate environment
    - script: '

        set "CI=azure"

        call activate base

        run_conda_forge_build_setup'
      displayName: conda-forge build setup
    - script: '

        set "CI=azure"

        call activate base


        @rem git clone https://github.com/thesnakepit/boa

        @rem cd boa

        @rem pip install -e .

        @rem cd ..


        conda config --append channels defaults

        conda config --add channels conda-forge

        conda config --add channels robostack

        conda config --set channel_priority strict


        @rem conda info

        @rem conda config --show-sources


        conda remove --force m2-git


        @rem conda list --show-channel-urls


        cp recipes/%CURRENT_BUILD_PKG_NAME%.yaml ./recipe.yaml


        boa build .


        @rem conda.exe build "recipe" -m .ci_support/%CONFIG%.yaml

        '
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_BUILD_PKG_NAME: ros-noetic-genmsg
        PYTHONUNBUFFERED: 1
      displayName: Build ros-noetic-genmsg
- stage: stage_2
  jobs:
  - job: ros_noetic_genpy
    variables:
      CONDA_BLD_PATH: C:\\bld\\
    steps:
    - task: CondaEnvironment@1
      inputs:
        packageSpecs: python=3.6 dataclasses conda-build conda conda-forge::conda-forge-ci-setup=3
          pip boa quetz-client
        installOptions: -c conda-forge/label/boa_dev -c conda-forge
        updateConda: true
      displayName: Install conda-build, boa and activate environment
    - script: '

        set "CI=azure"

        call activate base

        run_conda_forge_build_setup'
      displayName: conda-forge build setup
    - script: '

        set "CI=azure"

        call activate base


        @rem git clone https://github.com/thesnakepit/boa

        @rem cd boa

        @rem pip install -e .

        @rem cd ..


        conda config --append channels defaults

        conda config --add channels conda-forge

        conda config --add channels robostack

        conda config --set channel_priority strict


        @rem conda info

        @rem conda config --show-sources


        conda remove --force m2-git


        @rem conda list --show-channel-urls


        cp recipes/%CURRENT_BUILD_PKG_NAME%.yaml ./recipe.yaml


        boa build .


        @rem conda.exe build "recipe" -m .ci_support/%CONFIG%.yaml

        '
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_BUILD_PKG_NAME: ros-noetic-genpy
        PYTHONUNBUFFERED: 1
      displayName: Build ros-noetic-genpy
  - job: ros_noetic_cpp_common
    variables:
      CONDA_BLD_PATH: C:\\bld\\
    steps:
    - task: CondaEnvironment@1
      inputs:
        packageSpecs: python=3.6 dataclasses conda-build conda conda-forge::conda-forge-ci-setup=3
          pip boa quetz-client
        installOptions: -c conda-forge/label/boa_dev -c conda-forge
        updateConda: true
      displayName: Install conda-build, boa and activate environment
    - script: '

        set "CI=azure"

        call activate base

        run_conda_forge_build_setup'
      displayName: conda-forge build setup
    - script: '

        set "CI=azure"

        call activate base


        @rem git clone https://github.com/thesnakepit/boa

        @rem cd boa

        @rem pip install -e .

        @rem cd ..


        conda config --append channels defaults

        conda config --add channels conda-forge

        conda config --add channels robostack

        conda config --set channel_priority strict


        @rem conda info

        @rem conda config --show-sources


        conda remove --force m2-git


        @rem conda list --show-channel-urls


        cp recipes/%CURRENT_BUILD_PKG_NAME%.yaml ./recipe.yaml


        boa build .


        @rem conda.exe build "recipe" -m .ci_support/%CONFIG%.yaml

        '
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_BUILD_PKG_NAME: ros-noetic-cpp-common
        PYTHONUNBUFFERED: 1
      displayName: Build ros-noetic-cpp-common
- stage: stage_3
  jobs:
  - job: ros_noetic_rostime
    variables:
      CONDA_BLD_PATH: C:\\bld\\
    steps:
    - task: CondaEnvironment@1
      inputs:
        packageSpecs: python=3.6 dataclasses conda-build conda conda-forge::conda-forge-ci-setup=3
          pip boa quetz-client
        installOptions: -c conda-forge/label/boa_dev -c conda-forge
        updateConda: true
      displayName: Install conda-build, boa and activate environment
    - script: '

        set "CI=azure"

        call activate base

        run_conda_forge_build_setup'
      displayName: conda-forge build setup
    - script: '

        set "CI=azure"

        call activate base


        @rem git clone https://github.com/thesnakepit/boa

        @rem cd boa

        @rem pip install -e .

        @rem cd ..


        conda config --append channels defaults

        conda config --add channels conda-forge

        conda config --add channels robostack

        conda config --set channel_priority strict


        @rem conda info

        @rem conda config --show-sources


        conda remove --force m2-git


        @rem conda list --show-channel-urls


        cp recipes/%CURRENT_BUILD_PKG_NAME%.yaml ./recipe.yaml


        boa build .


        @rem conda.exe build "recipe" -m .ci_support/%CONFIG%.yaml

        '
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_BUILD_PKG_NAME: ros-noetic-rostime
        PYTHONUNBUFFERED: 1
      displayName: Build ros-noetic-rostime
- stage: stage_4
  jobs:
  - job: ros_noetic_roscpp_traits
    variables:
      CONDA_BLD_PATH: C:\\bld\\
    steps:
    - task: CondaEnvironment@1
      inputs:
        packageSpecs: python=3.6 dataclasses conda-build conda conda-forge::conda-forge-ci-setup=3
          pip boa quetz-client
        installOptions: -c conda-forge/label/boa_dev -c conda-forge
        updateConda: true
      displayName: Install conda-build, boa and activate environment
    - script: '

        set "CI=azure"

        call activate base

        run_conda_forge_build_setup'
      displayName: conda-forge build setup
    - script: '

        set "CI=azure"

        call activate base


        @rem git clone https://github.com/thesnakepit/boa

        @rem cd boa

        @rem pip install -e .

        @rem cd ..


        conda config --append channels defaults

        conda config --add channels conda-forge

        conda config --add channels robostack

        conda config --set channel_priority strict


        @rem conda info

        @rem conda config --show-sources


        conda remove --force m2-git


        @rem conda list --show-channel-urls


        cp recipes/%CURRENT_BUILD_PKG_NAME%.yaml ./recipe.yaml


        boa build .


        @rem conda.exe build "recipe" -m .ci_support/%CONFIG%.yaml

        '
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_BUILD_PKG_NAME: ros-noetic-roscpp-traits
        PYTHONUNBUFFERED: 1
      displayName: Build ros-noetic-roscpp-traits
- stage: stage_5
  jobs:
  - job: ros_noetic_roscpp_serialization
    variables:
      CONDA_BLD_PATH: C:\\bld\\
    steps:
    - task: CondaEnvironment@1
      inputs:
        packageSpecs: python=3.6 dataclasses conda-build conda conda-forge::conda-forge-ci-setup=3
          pip boa quetz-client
        installOptions: -c conda-forge/label/boa_dev -c conda-forge
        updateConda: true
      displayName: Install conda-build, boa and activate environment
    - script: '

        set "CI=azure"

        call activate base

        run_conda_forge_build_setup'
      displayName: conda-forge build setup
    - script: '

        set "CI=azure"

        call activate base


        @rem git clone https://github.com/thesnakepit/boa

        @rem cd boa

        @rem pip install -e .

        @rem cd ..


        conda config --append channels defaults

        conda config --add channels conda-forge

        conda config --add channels robostack

        conda config --set channel_priority strict


        @rem conda info

        @rem conda config --show-sources


        conda remove --force m2-git


        @rem conda list --show-channel-urls


        cp recipes/%CURRENT_BUILD_PKG_NAME%.yaml ./recipe.yaml


        boa build .


        @rem conda.exe build "recipe" -m .ci_support/%CONFIG%.yaml

        '
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_BUILD_PKG_NAME: ros-noetic-roscpp-serialization
        PYTHONUNBUFFERED: 1
      displayName: Build ros-noetic-roscpp-serialization
- stage: stage_6
  jobs:
  - job: ros_noetic_message_runtime
    variables:
      CONDA_BLD_PATH: C:\\bld\\
    steps:
    - task: CondaEnvironment@1
      inputs:
        packageSpecs: python=3.6 dataclasses conda-build conda conda-forge::conda-forge-ci-setup=3
          pip boa quetz-client
        installOptions: -c conda-forge/label/boa_dev -c conda-forge
        updateConda: true
      displayName: Install conda-build, boa and activate environment
    - script: '

        set "CI=azure"

        call activate base

        run_conda_forge_build_setup'
      displayName: conda-forge build setup
    - script: '

        set "CI=azure"

        call activate base


        @rem git clone https://github.com/thesnakepit/boa

        @rem cd boa

        @rem pip install -e .

        @rem cd ..


        conda config --append channels defaults

        conda config --add channels conda-forge

        conda config --add channels robostack

        conda config --set channel_priority strict


        @rem conda info

        @rem conda config --show-sources


        conda remove --force m2-git


        @rem conda list --show-channel-urls


        cp recipes/%CURRENT_BUILD_PKG_NAME%.yaml ./recipe.yaml


        boa build .


        @rem conda.exe build "recipe" -m .ci_support/%CONFIG%.yaml

        '
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_BUILD_PKG_NAME: ros-noetic-message-runtime
        PYTHONUNBUFFERED: 1
      displayName: Build ros-noetic-message-runtime
